### ISSUE TITLE
Failed to build with Qt 5.14

### ISSUE THREAD

**Issue by realw98** [linuxdeepin/deepin-system-monitor#34]
```
src/hashqstring.h:31:23: error: redefinition of ‘struct std::hash<QString>’
   31 |     template<> struct hash<QString>
```

 $ qmake --version
QMake version 3.1
Using Qt version 5.14.0 in /usr/lib64

**Comment by hillwoodroc** [comment]
Comfirmed this issues in openSUSE Tumbleweed.

**Comment by BLumia** [comment]
This hash is already defined in Qt 5.14, so simply remove the define inside `hashqstring.h` should works :)

Since the upstream development branch (for next major release, v20) is a lots of commits ahead of the current github master branch, maybe you can temporary apply a patch to this package for your distro to fix building under Qt 5.14.

**Comment by z966768** [comment]
We have made some changes,and the file`hashqstring.h`has been deleted. you can try again with the latest version

**Comment by felixonmars** [comment]
It should have been fixed.
